package com.claimsflow.claims.domain.ai;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Persisted AI summary for a claim, generated by Bedrock Claude.
 * One row per claim (UNIQUE on claim_ref).  Re-generation overwrites via upsert.
 */
@Entity
@Table(name = "ai_summaries")
@Getter
@NoArgsConstructor
public class AiSummary {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "claim_id", nullable = false)
    private Long claimId;

    @Column(name = "claim_ref", nullable = false, unique = true, length = 32)
    private String claimRef;

    @Column(name = "model_id", nullable = false, length = 128)
    private String modelId;

    @Column(name = "prompt_tokens")
    private Integer promptTokens;

    @Column(name = "completion_tokens")
    private Integer completionTokens;

    @Lob
    @Column(nullable = false)
    private String summary;

    @Column(name = "confidence_note", length = 500)
    private String confidenceNote;

    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;

    private AiSummary(Long claimId, String claimRef, String modelId, String summary) {
        this.claimId = claimId;
        this.claimRef = claimRef;
        this.modelId = modelId;
        this.summary = summary;
        this.generatedAt = Instant.now();
    }

    public static AiSummary create(Long claimId, String claimRef, String modelId, String summary) {
        return new AiSummary(claimId, claimRef, modelId, summary);
    }

    public void updateSummary(String newSummary) {
        this.summary = newSummary;
        this.generatedAt = Instant.now();
    }
}
