-- Week 2: AI summaries generated by AWS Bedrock Claude.
-- One row per claim (upserted on re-run). Stored in MySQL and also
-- projected into OpenSearch for full-text + facet search.

CREATE TABLE ai_summaries (
    id               BIGINT       NOT NULL AUTO_INCREMENT,
    claim_id         BIGINT       NOT NULL,
    claim_ref        VARCHAR(32)  NOT NULL,
    model_id         VARCHAR(128) NOT NULL,
    prompt_tokens    INT          NULL,
    completion_tokens INT         NULL,
    summary          TEXT         NOT NULL,
    confidence_note  VARCHAR(500) NULL,
    generated_at     TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_summaries_claim_ref (claim_ref),
    KEY idx_ai_summaries_claim_id (claim_id),
    CONSTRAINT fk_ai_summaries_claim FOREIGN KEY (claim_id) REFERENCES claims(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
